server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 1254
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: track-service
      auto-offset-reset: earliest
