server:
  port: 8084

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 1254
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: jRtuURMG37beZ8wSYZ1avaSbQZmiILHB
